#!/bin/bash

echo "🚀 SERWIS ZEBRA - INSTRUKCJA URUCHOMIENIA"
echo "=========================================="
echo ""
echo "1. Otwórz terminal w VS Code"
echo ""
echo "2. Przejdź do folderu projektu:"
echo "   cd /home/claude/serwiszebra"
echo ""
echo "3. Zainstaluj zależności (jeśli jeszcze nie zainstalowane):"
echo "   npm install"
echo ""
echo "4. Uruchom serwer deweloperski:"
echo "   npm run dev"
echo ""
echo "5. Otwórz przeglądarkę na:"
echo "   http://localhost:3000"
echo ""
echo "=========================================="
echo "✅ Projekt gotowy do pracy!"
echo ""
echo "Struktura projektu:"
echo "  /app/page.tsx - Strona główna"
echo "  /app/layout.tsx - Główny layout"
echo "  /app/globals.css - Style globalne"
echo ""
echo "Komendy:"
echo "  npm run dev - Tryb deweloperski"
echo "  npm run build - Build produkcyjny"
echo "  npm run start - Start produkcyjny"
