import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import ShopSubheader from '@/components/shop/ShopSubheader'
import CardMaterials from '@/components/shop/CardMaterials'
import {cardPrinterProducts} from '@/lib/card-printer-shop'
import {pobierzStany,stanDlaPN} from '@/lib/stock-server'
const URL='https://www.serwis-zebry.pl/sklep/drukarki-kart-zebra'
export const dynamic='force-dynamic'
export const metadata: Metadata={title:'Drukarki kart Zebra ZC100 i ZC300 — sklep | TAKMA',description:'Porównaj drukarki kart Zebra ZC100 i ZC300. Wybierz druk jednej lub obu stron. Sprawdź ceny, dostępność oraz zgodne taśmy i karty PVC.',alternates:{canonical:URL},openGraph:{title:'Drukarki kart Zebra — ZC100 i ZC300',url:URL,type:'website',locale:'pl_PL',images:['/sklep_photo/urzadzenia/zc300_1.webp']}}
const faq=[
 ['Jaką drukarkę Zebra wybrać do identyfikatorów?','Wybierz ZC100, jeśli potrzebujesz jednostronnego nadruku. Wybierz ZC300 w wersji ZC32, jeśli chcesz automatycznie drukować obie strony. Łączność i kodowanie dobierz według numeru PN.'],
 ['Czym różni się Zebra ZC100 od ZC300?','ZC100 drukuje jednostronnie, do 150 kolorowych kart/h. ZC300 drukuje jednostronnie do 200 kart/h, ma ekran LCD oraz wersje dwustronne. Podane prędkości dotyczą taśmy YMCKO i seryjnego druku przez USB.'],
 ['Czy drukarka kart Zebra zapisuje dane RFID?','Nadruk na karcie RFID nie zapisuje danych w jej układzie. Kodowanie wymaga zgodnego kodera, kart i oprogramowania. Przed zakupem podaj wymagania systemu kontroli dostępu.'],
 ['Co potrzebuję do rozpoczęcia druku kart?','Potrzebujesz drukarki, zgodnej kasety z taśmą, kart i programu do projektowania. Standardowe konfiguracje drukarek nie zawierają taśmy ani kart. Zestaw startowy ma osobny PN i określoną zawartość.'],
 ['Ile kosztuje wydruk jednej karty?','Koszt materiałów to cena taśmy podzielona przez liczbę wydruków oraz cena pustej karty. Do pełnego kosztu dodaj czyszczenie, odrzuty i eksploatację urządzenia. Wydajność taśmy zależy od jej PN i układu nadruku.'],
]
export default async function CardCategory(){
 const products=await cardPrinterProducts();const stock=await pobierzStany(products.flatMap(p=>p.variants.map(v=>v.pn)))
 const schema={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage','@id':URL,name:'Drukarki kart Zebra',url:URL,mainEntity:{'@id':URL+'#lista'}},{'@type':'ItemList','@id':URL+'#lista',itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:URL+'/'+p.slug}))},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Sklep',item:'https://www.serwis-zebry.pl/sklep'},{'@type':'ListItem',position:2,name:'Drukarki kart Zebra',item:URL}]}]}
 return <><Header currentPage="other"/><ShopSubheader breadcrumbs={[{label:'Sklep',href:'/sklep'},{label:'Drukarki kart Zebra',href:'/sklep/drukarki-kart-zebra'}]}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><main id="main-content" className="mx-auto max-w-6xl px-4 py-8">
 <h1 className="text-3xl font-semibold text-gray-900 sm:text-4xl">Drukarki kart Zebra</h1><p className="mt-4 max-w-3xl text-lg text-gray-700">Drukarki kart Zebra służą do tworzenia identyfikatorów, przepustek i kart członkowskich. Porównaj ZC100 oraz ZC300. Wybierz liczbę drukowanych stron, łączność i koder.</p>
 <nav aria-label="Na tej stronie" className="my-6 flex flex-wrap gap-4 text-sm text-blue-700 underline"><a href="#modele">Modele i ceny</a><a href="#porownanie">Porównanie</a><a href="#materialy">Taśmy i karty</a><a href="#pytania">Pytania</a><Link href="/serwis-drukarek-kart-zebra">Serwis drukarek kart</Link></nav>
 <section id="modele" className="grid gap-6 sm:grid-cols-2">{products.map(p=>{const offers=p.variants.map(v=>stanDlaPN(stock,v.pn)).filter(s=>s&&s.netto>0);const available=offers.filter(s=>s&&(s.stockPL+s.stockEU)>0);const prices=(available.length?available:offers).map(s=>s!.netto);return <article key={p.slug} className="rounded-2xl border border-gray-200 bg-white p-6"><Link href={'/sklep/drukarki-kart-zebra/'+p.slug}><Image src={p.images[0]} alt={p.name} width={480} height={360} className="h-64 w-full object-contain"/><h2 className="mt-4 text-2xl font-semibold">Zebra {p.model}</h2></Link><p className="mt-2 text-gray-600">{p.model==='ZC100'?'Druk jednostronny. USB; Ethernet i koder magnetyczny w wybranych konfiguracjach.':'Druk jednej lub obu stron, zależnie od PN. USB i Ethernet. Konfiguracje z koderem magnetycznym.'}</p><p className="mt-4 font-semibold">{prices.length?'Od '+Math.min(...prices).toLocaleString('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2})+' zł netto':'Zapytaj o cenę'}</p><p className="mt-1 text-sm text-gray-600">{available.length?'Dostępne konfiguracje w magazynie dystrybutora':'Sprawdź dostępność konfiguracji'} · {p.variants.length} warianty</p><Link className="mt-5 inline-flex min-h-12 items-center rounded-lg bg-[#A8F000] px-5 font-semibold" href={'/sklep/drukarki-kart-zebra/'+p.slug}>Wybierz wariant {p.model}</Link></article>})}</section>
 <section id="porownanie" className="mt-12"><h2 className="text-2xl font-semibold">Zebra ZC100 czy ZC300?</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Porównanie drukarek kart Zebra ZC100 i ZC300</caption><thead><tr className="bg-gray-100"><th className="p-3">Parametr</th><th className="p-3">ZC100</th><th className="p-3">ZC300</th></tr></thead><tbody>{[['Druk','Jednostronny','ZC31: jednostronny; ZC32: dwustronny'],['Kolor YMCKO, jedna strona','Do 150 kart/h','Do 200 kart/h'],['Kolor YMCKOK, obie strony','Brak','Do 140 kart/h'],['Rozdzielczość','300 dpi','300 dpi'],['Podajnik (karty 0,76 mm)','100 kart','100 kart'],['Łączność w tej ofercie','USB; Ethernet zależnie od PN','USB i Ethernet'],['Koder magnetyczny','Zależnie od PN','Zależnie od PN'],['Gwarancja producenta','3 lata na drukarkę i głowicę','3 lata na drukarkę i głowicę']].map(row=><tr key={row[0]} className="border-b border-gray-200"><th scope="row" className="p-3 font-medium">{row[0]}</th><td className="p-3">{row[1]}</td><td className="p-3">{row[2]}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-gray-600">Prędkości dotyczą druku seryjnego przez USB. Wynik zależy od komputera i zadania. Gwarancja wymaga użytkowania oraz konserwacji zgodnie z instrukcją.</p></section>
 <CardMaterials model="ZC100 i ZC300"/>
 <section className="my-10 rounded-xl bg-gray-50 p-6"><h2 className="text-2xl font-semibold">Zakup i obsługa drukarki kart</h2><p className="mt-3 text-gray-700">TAKMA dobiera konfiguracje i prowadzi serwis drukarek kart Zebra. Skorzystaj z instrukcji oraz filmów po polsku. Przed zakupem kodera ustalimy zgodność z Twoim systemem.</p><div className="mt-4 flex flex-wrap gap-4 text-blue-700 underline"><Link href="/serwis-drukarek-kart-zebra">Serwis ZC100 i ZC300</Link><Link href="/instrukcje/zebra-zc100/instrukcja-po-polsku">Instrukcja ZC100</Link><Link href="/instrukcje/zebra-zc300/instrukcja-po-polsku">Instrukcja ZC300</Link><Link href="/kontakt">Pomoc w wyborze</Link></div></section>
 <section id="pytania"><h2 className="text-2xl font-semibold">Pytania o drukarki kart Zebra</h2><div className="mt-5 space-y-4">{faq.map(([q,a])=><details key={q} className="rounded-lg border border-gray-200 p-4"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 max-w-3xl text-gray-700">{a}</p></details>)}</div></section>
 </main><Footer/></>
}
